UltricoBMI - Copy (2)/UltricoBMI.Web/Models/Shared/LanguageSelectorModel.cs
using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace UltricoBMI.Web.Models.Shared
{
    public class LanguageSelectorModel
    {
        public IList<CultureInfo> SupportedCultures { get; set; }

        public CultureInfo CurrentCulture
        {
            get { return Thread.CurrentThread.CurrentUICulture; }
        }
    }
}

UltricoBMI - Copy (2)/UltricoBMI.Web/Controllers/BMIController.cs
using System;
using System.Web.Mvc;
using UltricoBMI.Domain.BMIs.Commands;
using UltricoBMI.Domain.BMIs.Queries;
using UltricoBMI.Web.Infrastructure.Web;
using UltricoBMI.Web.Models.BMIs;

namespace UltricoBMI.Web.Controllers
{
    public class BMIController : BMIControllerBase
    {
        public ActionResult Index(BMISearchViewModel model)
        {
            return this.View("Search", model);
        }

        [HttpPost]
        public ActionResult Search(BMISearchViewModel model)
        {
            var queryResult = this.Query(new FindBMIQuery(model.ToModel()));
            model.SetResult(queryResult);
            return this.PartialView("_BMISearchResults", model);
        }

        [AllowAnonymous]
        public ActionResult NewBMI(NewBMICommand bmiCommand = null)
        {
            return this.View(bmiCommand != null ? new BMIViewModel(bmiCommand.ToPersonData()) : new BMIViewModel());
        }

        [HttpPost, AllowAnonymous]
        public ActionResult Calculate(NewBMICommand bmiCommand)
        {
            if (!ModelState.IsValid)
            {
                return View("NewBMI", new BMIViewModel(bmiCommand.ToPersonData()));
            }

            var cmdResult = this.ExecuteCommand(new NewBMICommandHandler(bmiCommand));

            return cmdResult.Success
                ? (ActionResult) this.RedirectToAction("Display", new { bmiId = cmdResult.Result })
                : this.View("NewBMI", new BMIViewModel(bmiCommand.ToPersonData()));
        }

        [AllowAnonymous]
        public ActionResult Display(Guid bmiId)
        {
            var result = new BMIViewModel(this.Query(new GetBMIQuery(bmiId)));
            return this.View(result);
        }
    }
}

UltricoBMI - Copy (2)/UltricoBMI.Web/Views/Shared/_Footer.cshtml
<footer>
    <hr />
    <p>© Rafał Krasowski - Ultrico BMI Intro - <strong>2014 - @DateTime.Now.Year</strong></p>
</footer>

UltricoBMI - Copy (2)/UltricoBMI.Web/Views/Shared/_LanguageSelector.cshtml
@model UltricoBMI.Web.Models.Shared.LanguageSelectorModel
@using UltricoBMI.Web.Infrastructure.Localization
@using UltricoBMI.Web.Resources

<ul class="nav pull-right">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            @Labels.LanguageSelector_Language @Html.Flag(Model.CurrentCulture)
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" role="menu"  aria-labelledby="dLabel">
            @foreach (var culture in Model.SupportedCultures)
            {
                <li><a tabindex="-1" href="#" onclick="switchLanguage('@culture.Name')">@Html.Flag(culture) @culture.DisplayName</a></li>
            }
        </ul>
    </li>           
</ul>

<script type="text/javascript">

    function switchLanguage(langCode) {
        $.cookie('locale', langCode, { path: '/'});
        window.location.reload();
    }

</script>

UltricoBMI - Copy (2)/UltricoBMI.Web/Views/Shared/_Layout.cshtml
@using UltricoBMI.Web.App_Start.Bundles

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>BMI Calculator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    @Styles.Render(BundlePaths.CSS.AllCSS)

    @Scripts.Render(BundlePaths.Scripts.JQuery)
    @Scripts.Render(BundlePaths.Scripts.Modernizer)
    @Scripts.Render(BundlePaths.Scripts.Bootstrap)

    @Scripts.Render(BundlePaths.Scripts.AllScripts)

</head>
<body>
    @Html.Partial("_MainMenu")

    <div class="container-fluid">
        <div class="row-fluid">
            <div>
                @RenderBody()
            </div>
        </div>
        <div class="row-fluid">
            <div>
                @Html.Partial("_Footer")
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(function () {
            Application.setCulture("@System.Globalization.CultureInfo.CurrentCulture.ToString()");
            });
    </script>

    @Html.Partial("_Routes")
</body>
</html>

UltricoBMI - Copy (2)/UltricoBMI.Web/Views/Shared/_MainMenu.cshtml
@using System.Globalization
@using UltricoBMI.Web
@using UltricoBMI.Web.Models.Shared
@using UltricoBMI.Web.Resources

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            @*<a href="@Url.Action("Index", "Home")">@Labels.AppTitle</a>*@

            <p class="navbar-text pull-right">
                @string.Format(Labels.LoggedInAs, Security.CurrentUserName)
            </p>

            @Html.Partial("_LanguageSelector", new LanguageSelectorModel
            {
                SupportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("en-GB"), 
                    new CultureInfo("pl-PL")
                }
            })
            
            <ul class="nav">
                <li><a href="@Url.Action("Index", "Home")">@Labels.Home_Title</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      @Labels.MainMenu_BMI
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Index", "BMI")">@Labels.BMI_Search_Title</a></li>
                        <li><a href="@Url.Action("NewBMI", "BMI")">@Labels.BMI_New_Title</a></li>
                    </ul>
                </li> 
                
            </ul>
        </div>
    </div>
</div>

UltricoBMI - Copy (2)/UltricoBMI.Web/Views/Shared/_Routes.cshtml
<script type="text/javascript">

    $(function() {

        Application.Routes = {

            Home: {
                Index:                  "@Url.Action("Index", "Home")"
            },

            BMI: {
                Search:                 "@Url.Action("Search", "BMI")",
                New:                    "@Url.Action("NewBMI", "BMI")",
            }
            
        };
    });
</script>